name: Validate TypeScript & check code formatting

# Triggered when code is pushed to any branch in a repository
on:
  push:
  workflow_dispatch:

# https://twitter.com/adamchainz/status/1485572084617121796?s=21
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci # npm ci is a CI environment specific installer https://stackoverflow.com/a/53325242

      - name: Validate TypeScript
        run: npm run ts:lint

      - name: ESLint
        run: npm run lint
