name: Validate TypeScript & check code formatting

# Triggered when code is pushed to any branch in a repository
on:
  push:
  pull_request:
  workflow_dispatch:

# https://twitter.com/adamchainz/status/1485572084617121796?s=21
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install Dependencies
        run: npm ci # npm ci is a CI environment specific installer https://stackoverflow.com/a/53325242

      - name: Validate TypeScript
        run: num run tsc:validate

      - name: ESLint
        run: npm run lint
