name: Check code formating

# Triggered when code is pushed to any branch in a repository
on: push

# https://twitter.com/adamchainz/status/1485572084617121796?s=21
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run checks
        run: npm run lint
